import Head from "next/head";
import { useState, useEffect } from "react";
import Link from "next/link";
import { supabase } from "../api";
import ClipLoader from "react-spinners/ClipLoader";

export default function Home() {
  const [posts, setPosts] = useState([]);
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    fetchPosts();
    const mySubscription = supabase
      .from("posts")
      .on("*", () => {
        fetchPosts();
      })
      .subscribe();
    return () => supabase.removeSubscription(mySubscription);
  }, []);
  async function fetchPosts() {
    const { data, error } = await supabase.from("post").select();
    setPosts(data);
    setLoading(false);
  }
  const truncate = (string, n) => {
    return string && string.length > n
      ? string.substr(0, n - 1) + "..."
      : string;
  };
  if (loading)
    return (
      <div className="flex items-center justify-center fixed w-full h-screen bg-opacity-60 bg-gray-500">
        <ClipLoader color="#2b94f0" loading={loading} size={50} />
      </div>
    );
  if (!posts.length)
    return (
      <div className="pt-20">
        <p className="text-2xl">No posts.</p>
      </div>
    );
  return (
    <div>
      <Head>
        <title>Nexlog</title>
        <meta name="description" content="generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-wrap justify-center gap-10 w-full pt-14 p-10 ">
        {posts.map((post) => (
          <Link key={post.id} href={`/posts/${post.id}`}>
            <div className="flex flex-col justify-evenly cursor-pointer w-11/12 md:max-w-11/12 md:w-72 h-32 border-b border-gray-300	mt-8 pb-4">
              <h2 className="text-xl font-semibold">{post.title}</h2>
              <p className="text-gray-500 ">Author: {post.user_email}</p>
              <p className="text-gray-500 ">{truncate(post.content,
                        50
                    )}</p>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}
